### ISSUE TITLE
Node 20 upgrade

### ISSUE THREAD

**Issue by arbrandes** [openedx/frontend-app-payment#858]
### Description

See the parent ticket for the general description and motivation, https://github.com/openedx/public-engineering/issues/267.  Make sure to follow its recommendations for each step of the process.

```[tasklist]
- [ ] https://github.com/openedx/frontend-app-payment/pull/879
- [ ] https://github.com/openedx/frontend-app-payment/pull/881
- [ ] https://github.com/openedx/frontend-app-payment/pull/889
```

**Comment by brian-smith-tcril** [comment]
#879 won't be able to land because of unrelated issues (see https://github.com/openedx/frontend-app-payment/pull/880). I think it makes sense to land #881 as it includes the changes from 879 and the required fixes.
